const $=s=>document.querySelector(s);

function renderTimeline(){const el=$("#timeline");if(!el||typeof timeline==="undefined")return;el.innerHTML=timeline.map(x=>`<article class="timeline-item reveal"><div class="timeline-date">${x.date}</div><h3>${x.title}</h3><p>${x.text}</p></article>`).join("")}
function gallery(){const g=$("#gallery"),empty=$("#photoEmpty");if(!g||typeof memories==="undefined")return;const a=memories.filter(x=>x.src);if(empty)empty.style.display=a.length?"none":"block";g.innerHTML=a.map(x=>`<article class="photo" data-src="${x.src}" data-title="${x.title||""}"><img loading="lazy" src="${x.src}" alt="${x.title||"Memory"}"><div class="photo-info"><strong>${x.title||""}</strong><small>${x.date||""}</small></div></article>`).join("");g.querySelectorAll(".photo").forEach(x=>x.onclick=()=>media(x.dataset.src,"img",x.dataset.title))}
function vids(){const g=$("#videosGrid"),empty=$("#videoEmpty");if(!g||typeof videos==="undefined")return;if(empty)empty.style.display=videos.length?"none":"block";g.innerHTML=videos.map(x=>`<article class="video" data-src="${x.src}" data-title="${x.title||""}"><div class="video-thumb">▶</div><h3>${x.title||"A moment"}</h3><p>${x.date||""} · ${x.description||""}</p></article>`).join("");g.querySelectorAll(".video").forEach(x=>x.onclick=()=>media(x.dataset.src,"video",x.dataset.title))}
function cards(){if(typeof letters!=="undefined"&&$("#lettersGrid"))$("#lettersGrid").innerHTML=letters.map(x=>`<article class="card reveal" data-text="${encodeURIComponent(x.text)}"><div class="tag">${x.tag}</div><h3>${x.title}</h3></article>`).join("");if(typeof openWhen!=="undefined"&&$("#openGrid"))$("#openGrid").innerHTML=openWhen.map(x=>`<article class="card reveal" data-text="${encodeURIComponent(x.text)}"><div class="tag">${x.tag}</div><h3>${x.title}</h3></article>`).join("");document.querySelectorAll(".card:not(.music-card)").forEach(x=>x.onclick=()=>text(decodeURIComponent(x.dataset.text),x.querySelector("h3").textContent))}
function renderThings(){const el=$("#things");if(!el||typeof things==="undefined")return;el.innerHTML=things.map((x,i)=>`<div class="thing reveal"><span>${String(i+1).padStart(2,"0")}</span><p>${x}</p></div>`).join("")}
function media(src,type,title){const content=$("#modalContent"),modal=$("#modal");if(!content||!modal)return;content.innerHTML=type==="img"?`<img src="${src}" alt="${title}">`:`<video src="${src}" controls autoplay playsinline></video>`;modal.classList.add("open");modal.setAttribute("aria-hidden","false")}
function text(t,title){const content=$("#modalContent"),modal=$("#modal");if(!content||!modal)return;content.innerHTML=`<div class="modal-text"><p class="micro">${title}</p><p>${t}</p></div>`;modal.classList.add("open");modal.setAttribute("aria-hidden","false")}
function close(){const modal=$("#modal"),content=$("#modalContent");if(modal){modal.classList.remove("open");modal.setAttribute("aria-hidden","true")}if(content)content.innerHTML=""}
const closeBtn=$("#close");if(closeBtn)closeBtn.onclick=close;const modal=$("#modal");if(modal)modal.onclick=e=>{if(e.target.id==="modal")close()};document.onkeydown=e=>{if(e.key==="Escape")close()};
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");io.unobserve(e.target)}}),{threshold:.12});function observe(){document.querySelectorAll(".reveal").forEach(x=>io.observe(x))}
function days(){const el=$("#days");if(!el)return;const start=new Date("2026-02-17T00:00:00+05:30");const n=Math.max(0,Math.floor((Date.now()-start)/86400000));el.textContent=n.toLocaleString("en-IN")}
const begin=$("#begin");if(begin)begin.onclick=()=>$("#story")?.scrollIntoView({behavior:"smooth"});const replay=$("#replay");if(replay)replay.onclick=()=>scrollTo({top:0,behavior:"smooth"});
let clicks=0;const secretBtn=$("#secretBtn");if(secretBtn)secretBtn.onclick=()=>{clicks++;if(clicks<3)secretBtn.textContent=`again... ${clicks}/3`;else{text("If you found this, congratulations, moon. You officially explored too much. I love you. ♡","A SECRET FOR MY BABY");secretBtn.textContent="found it ♡";secretBtn.disabled=true}};
document.addEventListener("mousemove",e=>{const c=$(".cursor-glow");if(c){c.style.left=e.clientX+"px";c.style.top=e.clientY+"px"}});
function setupMusic(){const music=$("#music"),mb=$("#musicBtn");if(!music)return;if(music.dataset.ready)return;music.dataset.ready="1";music.src=new URL("assets/audio/atlasaudio-love-piano-520077.mp3.mp3",document.baseURI).href;music.loop=true;music.preload="auto";music.volume=.28;music.addEventListener("error",()=>{if(mb)mb.textContent="♪";console.error("Background music failed to load",music.error)});if(mb)mb.onclick=()=>{if(music.paused){music.play().then(()=>mb.textContent="♫").catch(()=>mb.textContent="♪")}else{music.pause();mb.textContent="♪"}}}
function setupMenu(){const menu=$("#mobileMenu"),open=$("#menuBtn"),closeBtn=$("#mobileClose");if(!menu||!open)return;const toggle=v=>{menu.classList.toggle("open",v);menu.setAttribute("aria-hidden",String(!v))};open.onclick=()=>toggle(true);if(closeBtn)closeBtn.onclick=()=>toggle(false);menu.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>toggle(false)))}
function setupProgress(){const bar=$("#progress");if(!bar)return;const update=()=>{const h=document.documentElement.scrollHeight-innerHeight;bar.style.width=(h>0?scrollY/h*100:0)+"%"};addEventListener("scroll",update,{passive:true});update()}
function init(){try{renderTimeline()}catch(e){console.error("timeline",e)}try{gallery()}catch(e){console.error("gallery",e)}try{vids()}catch(e){console.error("videos",e)}try{cards()}catch(e){console.error("cards",e)}try{renderThings()}catch(e){console.error("things",e)}try{days()}catch(e){console.error("days",e)}try{observe()}catch(e){console.error("observe",e)}try{setupMusic()}catch(e){console.error("music",e)}try{setupMenu()}catch(e){console.error("menu",e)}try{setupProgress()}catch(e){console.error("progress",e)}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
